import React from "react";
import styles from "./PrintReport.module.css";

export default function PrintReport({
  dateFrom,
  dateTo,
  ecrFrom,
  ecrTo,
  orFrom,
  orTo,
  numberOfTransactions,
  totalCollection,
  cashBegin,
  cashSubmitted,
  cashEnd,
  AllTransactions,
  PerParticular,
  PerGradeLevel,
  ReportSummary,
  reportComponent,
  schoolName,
  ListPerParticular,
}) {
  return (
    <pre
      id="printReport"
      style={{ position: "absolute", left: "-9999em" }}
      className={styles.noSpace}
    >
      <p>
        Name of School: <span>{schoolName}</span>
      </p>
      <p>============================================================</p>
      <p>
        Generated by: <span>Sample data</span>
      </p>
      <p>
        Date: {dateFrom} - {dateTo}
      </p>
      <p>Cashier Name: Sample data</p>
      <p>
        ECR Number Series: {ecrFrom} - {ecrTo}
      </p>
      <p>
        OR Number Series: {orFrom} - {orTo}
      </p>
      <p>Number of Transactions: {numberOfTransactions}</p>
      <p>Total Collection (₱): {totalCollection.toLocaleString()}</p>
      <p>Cash on Hand (Begin) (₱): {Number(cashBegin).toLocaleString()}</p>
      <p>Cash Submitted (₱): {Number(cashSubmitted).toLocaleString()}</p>
      <p>Cash on Hand (End) (₱): {Number(cashEnd).toLocaleString()}</p>
      <p>============================================================</p>
      {reportComponent === "ALL TRANSACTIONS" && <AllTransactions />}
      {reportComponent === "PER PARTICULAR" && <PerParticular />}
      {reportComponent === "PER GRADE LEVEL" && <PerGradeLevel />}
      {reportComponent === "LIST PER PARTICULAR" && <ListPerParticular />}
      {reportComponent !== "ALL TRANSACTIONS" &&
        reportComponent !== "LIST PER PARTICULAR" && <ReportSummary />}
    </pre>
  );
}
